import {
  operationContext,
  type SysBOCreateInput,
  type SysBOEntity,
  type SysBOMetadata,
  type SysBOUpdateInput,
} from '@manatos/shared';

import type { AuditActor } from '../audit/audit-service.js';

import type { InMemoryDataStore } from '../storage/in-memory-data-store.js';

import type {
  InMemoryListAuthorizationFilter,
  InMemoryRepository,
  ListQuery,
  ListResult,
} from '../storage/in-memory-repository.js';

import { RelationshipIntegrityService, type DeleteImpactPlan } from './relationship-integrity-service.js';

/**
 * Generic application/service layer for metadata-driven SysBOs.
 *
 * Responsibilities:
 *
 * - expose standard CRUD operations;
 * - delegate actual data access to the injected repository;
 * - wrap mutating operations in datastore transactions;
 * - add semantic operation tracing around persistence operations.
 *
 * More specialized SysBO services can derive from this class and
 * add domain-specific validation or behavior.
 */
export class GenericSysBOService<T extends SysBOEntity> {
  constructor(
    protected readonly store: InMemoryDataStore,
    protected readonly repository: InMemoryRepository<T>,
    public readonly metadata: SysBOMetadata<T>,
  ) {}

  /**
   * Return a filtered, sorted and paginated list of entities.
   */
  async list(
    query: ListQuery,
    authorizationFilter?: InMemoryListAuthorizationFilter<T>,
  ): Promise<ListResult<T>> {
    return this.repository.list(query, authorizationFilter);
  }

  /**
   * Retrieve one entity by its generated GUID.
   *
   * Returns null when the entity does not exist.
   */
  async get(id: string): Promise<T | null> {
    return this.repository.getById(id);
  }

  /**
   * Create a new entity.
   *
   * Technical fields are generated by the storage layer:
   *
   * - id
   * - createdAt
   * - createdBy
   * - updatedAt
   * - updatedBy
   *
   * The repository is responsible for enforcing metadata-defined
   * uniqueness constraints.
   */
  async create(input: SysBOCreateInput<T>, actor: AuditActor): Promise<T> {
    return this.store.executeTransaction(() =>
      operationContext.run(
        `Create ${this.metadata.name} in data store`,

        async (scope) => {
          scope.comment('name', input.name);

          scope.comment('createdBy', actor.userName);

          return this.repository.create(input, actor);
        },
      ),
    );
  }

  /**
   * Update an existing entity.
   *
   * The repository is responsible for:
   *
   * - checking existence;
   * - enforcing metadata-defined uniqueness;
   * - updating updatedAt, updatedBy.
   */
  async update(id: string, changes: SysBOUpdateInput<T>, actor: AuditActor): Promise<T> {
    return this.store.executeTransaction(() =>
      operationContext.run(
        `Update ${this.metadata.name} in data store`,

        async (scope) => {
          scope.addContext({
            id,
            name: changes.name,
            updatedBy: actor.userName,
          });

          return this.repository.update(id, changes, actor);
        },
      ),
    );
  }

  /** Preview relationship-driven consequences before deleting this record. */
  deleteImpact(id: string): DeleteImpactPlan {
    return new RelationshipIntegrityService(this.store).previewDelete(this.metadata.key, id);
  }

  /**
   * Delete an existing entity by GUID. Referential effects are derived from
   * canonical relationship metadata; no entity-specific cascade code belongs
   * here.
   */
  async delete(id: string, actor: AuditActor): Promise<void> {
    await this.store.executeTransaction(() =>
      operationContext.run(
        `Delete ${this.metadata.name} from data store`,

        async (scope) => {
          scope.addContext({
            id,
            deletedBy: actor.userName,
          });

          new RelationshipIntegrityService(this.store).applyDeletePolicies(this.metadata.key, id);
          await this.repository.delete(id, actor);
        },
      ),
    );
  }
}
