import { operationContext, type SysBOEntity, type SysBOMetadata } from '@manatos/shared';

import type { InMemoryDataStore } from '../storage/in-memory-data-store.js';

import type { InMemoryRepository, ListQuery, ListResult } from '../storage/in-memory-repository.js';

/**
 * Generic application/service layer for metadata-driven SysBOs.
 *
 * Responsibilities:
 *
 * - expose standard CRUD operations;
 * - delegate actual data access to the injected repository;
 * - wrap mutating operations in datastore transactions;
 * - add semantic operation tracing around persistence operations.
 *
 * More specialized SysBO services can derive from this class and
 * add domain-specific validation or behavior.
 */
export class GenericSysBOService<T extends SysBOEntity> {
  constructor(
    protected readonly store: InMemoryDataStore,
    protected readonly repository: InMemoryRepository<T>,
    public readonly metadata: SysBOMetadata<T>,
  ) {}

  /**
   * Return a filtered, sorted and paginated list of entities.
   */
  async list(query: ListQuery): Promise<ListResult<T>> {
    return this.repository.list(query);
  }

  /**
   * Retrieve one entity by its generated GUID.
   *
   * Returns null when the entity does not exist.
   */
  async get(id: string): Promise<T | null> {
    return this.repository.getById(id);
  }

  /**
   * Create a new entity.
   *
   * Technical fields are generated by the storage layer:
   *
   * - id
   * - createdAt
   * - updatedAt
   */
  async create(input: Omit<T, 'id' | 'createdAt' | 'updatedAt'>): Promise<T> {
    return this.store.executeTransaction(() =>
      operationContext.run(
        `Create ${this.metadata.name} in data store`,

        async (scope) => {
          scope.comment('name', input.name);

          return this.repository.create(input);
        },
      ),
    );
  }

  /**
   * Update an existing entity.
   *
   * The repository is responsible for:
   *
   * - checking existence;
   * - enforcing metadata-defined uniqueness;
   * - updating updatedAt.
   */
  async update(id: string, changes: Partial<T>): Promise<T> {
    return this.store.executeTransaction(() =>
      operationContext.run(
        `Update ${this.metadata.name} in data store`,

        async (scope) => {
          scope.addContext({
            id,
            name: changes.name,
          });

          return this.repository.update(id, changes);
        },
      ),
    );
  }

  /**
   * Delete an existing entity by GUID.
   */
  async delete(id: string): Promise<void> {
    await this.store.executeTransaction(() =>
      operationContext.run(
        `Delete ${this.metadata.name} from data store`,

        async (scope) => {
          scope.comment('id', id);

          await this.repository.delete(id);
        },
      ),
    );
  }
}
