import {SysUserRole,sysApplicationsMetadata,sysLicensesMetadata,sysPrincipalsMetadata,sysUsersMetadata} from '@manatos/shared';import type {SysBODefinition,SysBOPaginationConfiguration} from './types.js';
const admin=[SysUserRole.Admin],p:SysBOPaginationConfiguration={enabled:true,defaultPageSize:20,allowedPageSizes:[10,20,50,100],maxPageSize:100,showPageSizeSelector:true,showFirstLastButtons:true,maxVisiblePageButtons:7};
const perms={view:admin,create:admin,edit:admin,delete:admin};
export const sysBODefinitions:Record<string,SysBODefinition>={
 'sys-users':{key:'sys-users',boMetadata:sysUsersMetadata,uiMetadata:{icon:'bi-person-circle',listViewModel:{title:'Users',addButtonText:'Add new',showResultCount:true},editViewModel:{createTitle:'Add User',editTitle:'Edit User',showDeleteButton:true,confirmUnsavedChanges:true},gridConfiguration:{allowSorting:true,allowFiltering:true,responsive:true,visibleFields:['name','email','role','emailVerified','enabled']},filterDefinition:{mode:'and',allowMultipleFilters:true,fields:['name','email','role']},paginationConfiguration:p},permissions:perms},
 'sys-principals':{key:'sys-principals',boMetadata:sysPrincipalsMetadata,uiMetadata:{icon:'bi-person-circle',listViewModel:{title:'Principals / Customers',addButtonText:'Add new',showResultCount:true},editViewModel:{createTitle:'Add Principal',editTitle:'Edit Principal',showDeleteButton:true,confirmUnsavedChanges:true},gridConfiguration:{allowSorting:true,allowFiltering:true,responsive:true,visibleFields:['name','principalType','parentId','enabled']},filterDefinition:{mode:'and',allowMultipleFilters:true,fields:['name','principalType']},paginationConfiguration:p},permissions:perms},
 'sys-applications':{key:'sys-applications',boMetadata:sysApplicationsMetadata,uiMetadata:{icon:'bi-window-stack',listViewModel:{title:'Applications',addButtonText:'Add new',showResultCount:true},editViewModel:{createTitle:'Add Application',editTitle:'Edit Application',showDeleteButton:true,confirmUnsavedChanges:true},gridConfiguration:{allowSorting:true,allowFiltering:true,responsive:true,showPlayAction:true,visibleFields:['name','appName','fullName','version','enabled']},filterDefinition:{mode:'and',allowMultipleFilters:true,fields:['name','appName','fullName']},paginationConfiguration:p},permissions:perms},
 'sys-licenses':{key:'sys-licenses',boMetadata:sysLicensesMetadata,uiMetadata:{icon:'bi-key',listViewModel:{title:'Licenses',addButtonText:'Add new',showResultCount:true},editViewModel:{createTitle:'Add License',editTitle:'Edit License',showDeleteButton:true,confirmUnsavedChanges:true},gridConfiguration:{allowSorting:true,allowFiltering:true,responsive:true,visibleFields:['name','principalId','applicationId','status','validUntil','enabled']},filterDefinition:{mode:'and',allowMultipleFilters:true,fields:['name','status']},paginationConfiguration:p},permissions:perms}
};
export function getSysBODefinition(k:string){const d=sysBODefinitions[k];if(!d)throw new Error(`Unknown SysBO '${k}'.`);return d;}
