import {Router} from 'express';import {AppError,operationContext,validatePassword,type SysUser} from '@manatos/shared';import {apiClient} from '../api-client.js';import {emailService} from '../email/email-service.js';import {securityTokenStore} from '../security/security-token-store.js';import {passport,configuredProviders,type ExternalProfile} from '../auth/passport.js';import {requireCsrf} from '../middleware/csrf.js';import {renderPage} from '../render.js';
export function createAuthRouter(){const r=Router();
 r.post('/signin/local',requireCsrf,async(q,res,n)=>{try{await operationContext.runRoot('Sign in with email/user-name and password',async s=>{s.addContext({identity:q.body.identity,password:q.body.password});const u=(await apiClient.post<SysUser>('/api/v1/internal/auth/verify-local',{identity:q.body.identity,password:q.body.password},true)).data;await regen(q);q.session.userId=u.id;q.session.authenticationMethod='local';res.redirect('/account');},'Signing in');}catch(e){n(e);}});
 r.post('/register/email',requireCsrf,async(q,res,n)=>{try{await operationContext.runRoot('Register website account by email',async s=>{s.addContext({name:q.body.name,email:q.body.email,password:q.body.password});if(q.body.password!==q.body.confirmPassword)throw new AppError('PASSWORD_CONFIRMATION_MISMATCH','Password confirmation mismatch.','The two password values do not match.');const f=validatePassword(String(q.body.password??''));if(f.length)throw new AppError('PASSWORD_POLICY',f.join(' '),f.join(' '));const u=(await apiClient.post<SysUser>('/api/v1/SysUsers',{name:q.body.name,email:q.body.email,password:q.body.password,role:'Guest',emailVerified:false,enabled:true})).data;const token=securityTokenStore.create(u.id,'verify-email',1440);await emailService.sendWelcomeAndVerificationEmail(u,abs(q,`/auth/verify-email?token=${encodeURIComponent(token)}`));await regen(q);q.session.userId=u.id;q.session.authenticationMethod='email-registration';res.redirect('/account');},'Creating your account');}catch(e){n(e);}});
 r.get('/verify-email',async(q,res,n)=>{try{const id=securityTokenStore.consume(String(q.query.token??''),'verify-email');if(!id)throw new AppError('INVALID_TOKEN','Invalid verification token.','The verification link is invalid or expired.');await apiClient.put(`/api/v1/internal/SysUsers/${id}/email-verified`,{},true);res.redirect('/account?message=email-verified');}catch(e){n(e);}});
 r.post('/password/request',requireCsrf,async(q,res)=>{try{const u=await lookup(String(q.body.identity??''));if(u){const token=securityTokenStore.create(u.id,'reset-password',30);await emailService.sendPasswordResetEmail(u,abs(q,`/auth/password/reset?token=${encodeURIComponent(token)}`));}}catch{}res.redirect('/?message=password-instructions');});
 r.get('/password/reset',async(q,res)=>renderPage(res,'pages/password-reset',{title:'Set or reset password',token:String(q.query.token??'')}));
 r.post('/password/reset',requireCsrf,async(q,res,n)=>{try{const p=String(q.body.password??'');if(p!==String(q.body.confirmPassword??''))throw new AppError('PASSWORD_CONFIRMATION_MISMATCH','Password confirmation mismatch.','The two password values do not match.');const f=validatePassword(p);if(f.length)throw new AppError('PASSWORD_POLICY',f.join(' '),f.join(' '));const id=securityTokenStore.consume(String(q.body.token??''),'reset-password');if(!id)throw new AppError('INVALID_TOKEN','Invalid reset token.','The password link is invalid or expired.');const u=(await apiClient.put<SysUser>(`/api/v1/internal/SysUsers/${id}/password`,{password:p},true)).data;await emailService.sendPasswordChangedEmail(u);res.redirect('/?message=password-changed');}catch(e){n(e);}});
 r.get('/logout',(q,res,n)=>q.session.destroy(e=>e?n(e):res.redirect('/')));
 for(const p of configuredProviders()){
   r.get(`/${p.key}`,passport.authenticate(p.key,{session:false}));
   r.get(`/${p.key}/callback`,passport.authenticate(p.key,{session:false,failureRedirect:'/?auth=failed'}),async(q,res,n)=>{try{const profile=q.authInfo?.externalProfile;if(!profile)throw new Error('External profile not supplied.');const linked=await resolveExternal(profile);if(linked){await regen(q);q.session.userId=linked.id;q.session.authenticationMethod=profile.provider;res.redirect('/account');return;}const existing=await lookup(profile.email);if(existing)throw new AppError('SYSUSER_EMAIL_ALREADY_EXISTS',`Email ${profile.email} is already registered.`,'This email is already registered. Please sign in to the existing account or use account recovery.');q.session.pendingExternalRegistration=profile;res.redirect('/auth/register/external');}catch(e){n(e);}});
 }
 r.get('/register/external',async(q,res)=>{if(!q.session.pendingExternalRegistration){res.redirect('/');return;}await renderPage(res,'pages/external-registration',{title:'Complete registration',profile:q.session.pendingExternalRegistration});});
 r.post('/register/external',requireCsrf,async(q,res,n)=>{try{const p=q.session.pendingExternalRegistration;if(!p)throw new Error('External registration session expired.');const pass=String(q.body.password??'');if(pass&&pass!==String(q.body.confirmPassword??''))throw new AppError('PASSWORD_CONFIRMATION_MISMATCH','Password confirmation mismatch.','The two password values do not match.');if(pass){const f=validatePassword(pass);if(f.length)throw new AppError('PASSWORD_POLICY',f.join(' '),f.join(' '));}const u=(await apiClient.post<SysUser>('/api/v1/SysUsers',{name:q.body.name,email:p.email,...(pass?{password:pass}:{}),role:'Guest',emailVerified:p.emailVerified,...(p.firstName?{firstName:p.firstName}:{}),...(p.lastName?{lastName:p.lastName}:{}),enabled:true})).data;await apiClient.post(`/api/v1/internal/SysUsers/${u.id}/external-identities`,{provider:p.provider,providerSubject:p.providerSubject,email:p.email,emailVerified:p.emailVerified,displayName:p.displayName},true);const verify=p.emailVerified?undefined:abs(q,`/auth/verify-email?token=${encodeURIComponent(securityTokenStore.create(u.id,'verify-email',1440))}`);await emailService.sendWelcomeAndVerificationEmail(u,verify);await regen(q);q.session.userId=u.id;q.session.authenticationMethod=p.provider;q.session.pendingExternalRegistration=undefined;res.redirect('/account');}catch(e){n(e);}});
 return r;}
async function lookup(identity:string):Promise<SysUser|null>{const a=await apiClient.get<SysUser[]>(`/api/v1/SysUsers?filter.name=${encodeURIComponent(identity)}&pageSize=2`);const n=a.data.find(u=>u.name.toLowerCase()===identity.toLowerCase());if(n)return n;const b=await apiClient.get<SysUser[]>(`/api/v1/SysUsers?filter.email=${encodeURIComponent(identity)}&pageSize=2`);return b.data.find(u=>u.email.toLowerCase()===identity.toLowerCase())??null;}
async function resolveExternal(p:ExternalProfile):Promise<SysUser|null>{const x=await apiClient.get<{userId:string}|null>(`/api/v1/internal/external-identities/resolve?provider=${encodeURIComponent(p.provider)}&subject=${encodeURIComponent(p.providerSubject)}`,true);return x.data?.userId?(await apiClient.get<SysUser>(`/api/v1/SysUsers/${x.data.userId}`)).data:null;}
function regen(q:import('express').Request){return new Promise<void>((ok,bad)=>q.session.regenerate(e=>e?bad(e):ok()));}function abs(q:import('express').Request,path:string){return `${q.protocol}://${q.get('host')}${path}`;}
