import {Router} from 'express';import {AppError,operationContext} from '@manatos/shared';import {apiClient} from '../api-client.js';import {requireAdmin,requireSignedIn} from '../middleware/auth.js';import {requireCsrf} from '../middleware/csrf.js';import {renderPage} from '../render.js';import {addSessionError} from '../errors/session-error-log.js';import {getSysBODefinition} from '../sysbo/definitions.js';
const pathByKey:Record<string,string>={'sys-users':'SysUsers','sys-principals':'SysPrincipals','sys-applications':'SysApplications','sys-licenses':'SysLicenses'};
export function createSysBORoutes(){const r=Router();r.use(requireSignedIn,requireAdmin);
 r.get('/:key',async(q,res,n)=>{try{const d=getSysBODefinition(q.params.key),api=pathByKey[d.key],params=listQuery(q,d),x=await apiClient.get<Record<string,unknown>[]>(`/api/v1/${api}?${params}`);await renderPage(res,'pages/bo-list',{title:d.uiMetadata.listViewModel.title,definition:d,items:x.data,paging:x.paging,query:q.query});}catch(e){n(e);}});
 r.get('/:key/new',async(q,res,n)=>{try{const d=getSysBODefinition(q.params.key);await renderPage(res,'pages/bo-edit',{title:d.uiMetadata.editViewModel.createTitle,definition:d,item:{},isNew:true,referenceData:await references(d)});}catch(e){n(e);}});
 r.get('/:key/:id',async(q,res,n)=>{try{const d=getSysBODefinition(q.params.key),api=pathByKey[d.key],item=(await apiClient.get<Record<string,unknown>>(`/api/v1/${api}/${q.params.id}`)).data;await renderPage(res,'pages/bo-edit',{title:d.uiMetadata.editViewModel.editTitle,definition:d,item,isNew:false,referenceData:await references(d)});}catch(e){n(e);}});
 r.post('/:key/save',requireCsrf,async(q,res,n)=>{const d=getSysBODefinition(q.params.key),api=pathByKey[d.key],id=String(q.body.id??'');try{await operationContext.runRoot(`${id?'Update':'Create'} ${d.boMetadata.name}`,async s=>{s.addContext({id,name:q.body.name});const payload=formPayload(q.body,d);if(id)await apiClient.patch(`/api/v1/${api}/${id}`,payload);else await apiClient.post(`/api/v1/${api}`,payload);res.redirect(`/bo/${d.key}`);},`Saving ${d.boMetadata.name}`);}catch(e){const a=e instanceof AppError?e:new AppError('UNEXPECTED_ERROR',String(e),'The entry could not be saved.',true);addSessionError(q,a);await renderPage(res,'pages/bo-edit',{title:id?d.uiMetadata.editViewModel.editTitle:d.uiMetadata.editViewModel.createTitle,definition:d,item:{...q.body,id},isNew:!id,referenceData:await references(d),applicationError:a});}});
 r.post('/:key/:id/delete',requireCsrf,async(q,res,n)=>{try{const d=getSysBODefinition(q.params.key);await operationContext.runRoot(`Delete ${d.boMetadata.name}`,async()=>apiClient.delete(`/api/v1/${pathByKey[d.key]}/${q.params.id}`));res.redirect(`/bo/${d.key}`);}catch(e){n(e);}});
 r.get('/sys-applications/:id/play',async(q,res,n)=>{try{q.session.activeApplicationId=q.params.id;const app=(await apiClient.get<Record<string,unknown>>(`/api/v1/SysApplications/${q.params.id}`)).data;await renderPage(res,'pages/application-playground',{title:`${String(app.name)} Playground`,application:app});}catch(e){n(e);}});return r;}
function listQuery(q:import('express').Request,d:ReturnType<typeof getSysBODefinition>){const p=new URLSearchParams();p.set('page',String(q.query.page??1));p.set('pageSize',String(q.query.pageSize??d.uiMetadata.paginationConfiguration.defaultPageSize));if(typeof q.query.sort==='string')p.set('sort',q.query.sort);if(q.query.direction==='desc')p.set('direction','desc');for(const f of d.uiMetadata.filterDefinition.fields){const v=q.query[`filter.${f}`];if(typeof v==='string'&&v)p.set(`filter.${f}`,v);}return p.toString();}
function formPayload(body:Record<string,unknown>,d:ReturnType<typeof getSysBODefinition>){const out:Record<string,unknown>={};for(const f of Object.values(d.boMetadata.fieldDefinition)){if(f.generated||f.readOnly||f.sensitive)continue;const raw=body[f.key];if(f.type==='boolean')out[f.key]=raw==='on'||raw==='true'||raw===true;else if(f.type==='number')out[f.key]=Number(raw??0);else if(raw!==undefined&&raw!=='')out[f.key]=raw;else if(f.nullable)out[f.key]=null;}return out;}
async function references(d:ReturnType<typeof getSysBODefinition>){const out:Record<string,unknown[]>={};for(const f of Object.values(d.boMetadata.fieldDefinition)){if(!f.referenceBOKey)continue;const api=pathByKey[f.referenceBOKey];if(api)out[f.key]=(await apiClient.get<unknown[]>(`/api/v1/${api}?pageSize=500&sort=name`)).data;}return out;}
