/**
 * Base persisted business-object record.
 *
 * The active storage provider generates the Id.
 */
export interface SysBOEntity {
  id: string;
  name: string;

  createdAt: string;
  createdBy: string;

  updatedAt: string;
  updatedBy: string;

  enabled: boolean;
}

/**
 * Input used when creating a persisted SysBO.
 *
 * Technical identity and audit properties are always generated by
 * the persistence/application infrastructure and are never supplied
 * by an API caller.
 */
export type SysBOCreateInput<T extends SysBOEntity> = Omit<
  T,
  'id' | 'createdAt' | 'createdBy' | 'updatedAt' | 'updatedBy'
>;

/**
 * Input used when updating a persisted SysBO.
 *
 * Identity and audit properties cannot be changed through normal
 * business-object updates.
 */
export type SysBOUpdateInput<T extends SysBOEntity> = Partial<
  Omit<T, 'id' | 'createdAt' | 'createdBy' | 'updatedAt' | 'updatedBy'>
>;

/**
 * Website user security roles.
 */
export enum SysExtAuthProviderType {
  Microsoft = 'microsoft',
  Google = 'google',
  Facebook = 'facebook',
  GitHub = 'github',
}

/** Company-owned configuration for one supported external authentication provider. */
export interface SysExtAuthProvider extends SysBOEntity {
  provider: SysExtAuthProviderType;
  clientId: string;
  /** Encrypted persistence-only OAuth client secret. Never expose through API/UI. */
  clientSecretEncrypted?: string | null;
  callbackPath: string;
  tenant?: string;
  secretUpdatedAt?: string | null;

  /**
   * Timestamp of the most recent successful end-to-end OAuth credential test.
   *
   * This is cleared whenever the stored Client ID/secret pair changes or is
   * removed. A provider is runtime-configured only while this verification is
   * present together with both credential values.
   */
  credentialsVerifiedAt?: string | null;
}

export enum SysUserRole {
  Admin = 'Admin',
  Superuser = 'Superuser',
  User = 'User',
  Guest = 'Guest',
}

/**
 * Source that established trust in a SysUser email address.
 *
 * `internal` means ManatOS verified the email itself (verification link or
 * an explicitly authorized administrative/internal action). External
 * providers are recorded by their stable provider key.
 */
export const EXTERNAL_PROVIDER_KEYS = ['google', 'facebook', 'github', 'microsoft'] as const;

export type ExternalProviderKey = (typeof EXTERNAL_PROVIDER_KEYS)[number];

export type EmailVerificationSource = 'internal' | ExternalProviderKey;

export function isExternalProviderKey(value: string): value is ExternalProviderKey {
  return (EXTERNAL_PROVIDER_KEYS as readonly string[]).includes(value);
}

/**
 * Supported customer/commercial principal types.
 */
export enum SysPrincipalType {
  Person = 'Person',
  Company = 'Company',
  Group = 'Group',
  System = 'System',
}

/**
 * Supported license states.
 */
export enum SysLicenseStatus {
  Active = 'Active',
  Suspended = 'Suspended',
  Expired = 'Expired',
  Cancelled = 'Cancelled',
}

/**
 * Defines the relationship between a website user
 * and a customer/commercial principal.
 */
export enum SysUserPrincipalRelationship {
  Owner = 'Owner',
  Administrator = 'Administrator',
  Member = 'Member',
  Representative = 'Representative',
}

/**
 * Website/security identity.
 *
 * `name` is the unique local user-name.
 * `email` is also unique.
 *
 * A SysUser represents a website account and is deliberately
 * separated from SysPrincipal, which represents a customer or
 * other commercial identity.
 */
export interface SysUser extends SysBOEntity {
  email: string;
  emailVerified: boolean;

  /** When and how the current email address became verified. */
  emailVerifiedAt?: string | null;
  emailVerificationSource?: EmailVerificationSource | null;

  /**
   * Contains the securely hashed password when the user has
   * configured local authentication.
   *
   * It may be null for accounts that authenticate exclusively
   * through an external identity provider.
   */
  passwordHash: string | null;

  passwordChangedAt: string | null;

  role: SysUserRole;

  firstName?: string;
  lastName?: string;
  description?: string;
}

/**
 * Customer/commercial identity.
 *
 * A SysPrincipal does not authenticate directly.
 *
 * Authentication belongs to SysUser, while SysUserPrincipal
 * establishes the relationship between users and principals.
 */
export interface SysPrincipal extends SysBOEntity {
  principalType: SysPrincipalType;

  /**
   * Optional parent principal.
   *
   * Children do not need to be persisted separately because they
   * can be obtained by finding principals whose parentId refers
   * to this principal.
   */
  parentId: string | null;

  description?: string;
}

/**
 * Application known and managed by the platform.
 */
export interface SysApplication extends SysBOEntity {
  /**
   * Unique application-specific name.
   */
  appName: string;

  fullName: string;

  description?: string;
  version?: string;
}

/**
 * License associating a customer/commercial principal
 * with an application.
 */
export interface SysLicense extends SysBOEntity {
  /** Company-owned principal receiving the entitlement. */
  principalId: string;

  /** Exactly one platform is licensed by each SysLicense. */
  platformId: string;

  /**
   * Optional single-application restriction retained for backward compatibility.
   *
   * A null/omitted value represents a platform-wide license. A future richer
   * entitlement model can represent one-or-many applications and design rights
   * without changing the principal -> license -> platform ownership model.
   */
  applicationId?: string | null;

  licenseKey?: string;

  status: SysLicenseStatus;

  validFrom?: string;
  validUntil?: string | null;

  quantity: number;

  description?: string;
}

/**
 * External authentication identity associated with a SysUser.
 *
 * Examples of providers may include:
 *
 * - Google
 * - Facebook
 * - other OAuth/OIDC providers added later
 *
 * A SysUser may therefore authenticate through an external
 * provider without necessarily having a local password.
 */
export interface SysExternalIdentity extends SysBOEntity {
  userId: string;

  provider: string;
  providerSubject: string;

  email?: string;
  emailVerified?: boolean;
  displayName?: string;
}

/**
 * Relationship between a website SysUser and a
 * customer/commercial SysPrincipal.
 *
 * This allows:
 *
 * - one user to relate to multiple principals;
 * - one principal to relate to multiple users;
 * - the relationship type to describe the user's authority
 *   or association with that principal.
 */
export interface SysUserPrincipal extends SysBOEntity {
  userId: string;
  principalId: string;

  relationship: SysUserPrincipalRelationship;

  /**
   * Indicates the principal that should normally become the
   * user's active/default customer context.
   */
  isDefault: boolean;

  description?: string;
}

/**
 * Persistable invitation scaffold for customers created before
 * a website account exists.
 *
 * This supports the scenario where a customer/principal exists
 * before the corresponding person has registered a SysUser.
 *
 * `tokenHash` stores only a hash.
 *
 * The raw activation token must exist only in the invitation
 * email and must never be persisted.
 */
export interface SysUserInvitation extends SysBOEntity {
  email: string;

  principalId: string;

  relationship: SysUserPrincipalRelationship;

  requestedRole: SysUserRole;

  tokenHash: string;

  expiresAt: string;

  usedAt: string | null;
}
