/**
 * Base persisted business-object record.
 *
 * The active storage provider generates the Id.
 */
export interface SysBOEntity {
  id: string;
  name: string;

  createdAt: string;
  createdBy: string;

  updatedAt: string;
  updatedBy: string;

  enabled: boolean;
}

/**
 * Input used when creating a persisted SysBO.
 *
 * Technical identity and audit properties are always generated by
 * the persistence/application infrastructure and are never supplied
 * by an API caller.
 */
export type SysBOCreateInput<T extends SysBOEntity> = Omit<
  T,
  'id' | 'createdAt' | 'createdBy' | 'updatedAt' | 'updatedBy'
>;

/**
 * Input used when updating a persisted SysBO.
 *
 * Identity and audit properties cannot be changed through normal
 * business-object updates.
 */
export type SysBOUpdateInput<T extends SysBOEntity> = Partial<
  Omit<T, 'id' | 'createdAt' | 'createdBy' | 'updatedAt' | 'updatedBy'>
>;

/** Runtime configuration value types. */
export type SysBOConfigurationValueType = 'string' | 'number' | 'boolean' | 'enum' | 'secret';

/**
 * Persisted application configuration. Sensitive values are stored only in
 * valueEncrypted; normal API/UI projections never expose that envelope.
 */
export interface SysBOConfiguration extends SysBOEntity {
  value: string | null;
  valueEncrypted?: string | null;
  group: string;
  description?: string;
  valueType: SysBOConfigurationValueType;
  allowedValues?: string[];
  defaultValue?: string | null;
  restartRequired?: boolean;
  editable: boolean;
  sensitive: boolean;
}

/**
 * Website user security roles.
 */
export enum SysBOExtAuthProviderType {
  Microsoft = 'microsoft',
  Google = 'google',
  Facebook = 'facebook',
  GitHub = 'github',
}

/** Company-owned configuration for one supported external authentication provider. */
export interface SysBOExtAuthProvider extends SysBOEntity {
  provider: SysBOExtAuthProviderType;
  clientId: string;
  /** Encrypted persistence-only OAuth client secret. Never expose through API/UI. */
  clientSecretEncrypted?: string | null;
  callbackPath: string;
  tenant?: string;
  secretUpdatedAt?: string | null;

  /**
   * Persisted, application-managed verification state for the currently
   * stored Client ID + Client secret pair. Admin/API callers cannot set this
   * directly; credential lifecycle commands maintain it atomically.
   */
  credentialsVerified: boolean;

  /**
   * Timestamp of the most recent successful end-to-end OAuth credential test.
   * Cleared whenever the stored credential pair changes or is removed.
   */
  credentialsVerifiedAt?: string | null;
}

export enum SysBOUserRole {
  Admin = 'Admin',
  Superuser = 'Superuser',
  User = 'User',
  Guest = 'Guest',
}

/**
 * Source that established trust in a SysBOUser email address.
 *
 * `internal` means ManatOS verified the email itself (verification link or
 * an explicitly authorized administrative/internal action). External
 * providers are recorded by their stable provider key.
 */
export const EXTERNAL_PROVIDER_KEYS = ['google', 'facebook', 'github', 'microsoft'] as const;

export type ExternalProviderKey = (typeof EXTERNAL_PROVIDER_KEYS)[number];

export type EmailVerificationSource = 'internal' | ExternalProviderKey;

export function isExternalProviderKey(value: string): value is ExternalProviderKey {
  return (EXTERNAL_PROVIDER_KEYS as readonly string[]).includes(value);
}

/**
 * Supported customer/commercial principal types.
 */
export enum SysBOPrincipalType {
  Person = 'Person',
  Company = 'Company',
  Group = 'Group',
  System = 'System',
}

/**
 * Supported license states.
 */

/**
 * Calendar-aware duration used by reusable metadata-driven duration fields.
 *
 * The parts deliberately preserve calendar semantics: one month is not reduced
 * to a fixed number of days, and one year remains a calendar year.
 */
export interface SysBODurationValue {
  years: number;
  months: number;
  days: number;
}

export enum SysBOLicenseStatus {
  Active = 'Active',
  Suspended = 'Suspended',
  Expired = 'Expired',
  Cancelled = 'Cancelled',
}

/**
 * Defines the relationship between a website user
 * and a customer/commercial principal.
 */
export enum SysBOUserPrincipalRelationship {
  Owner = 'Owner',
  Administrator = 'Administrator',
  Member = 'Member',
  Representative = 'Representative',
}

/**
 * Website/security identity.
 *
 * `name` is the unique local user-name.
 * `email` is also unique.
 *
 * A SysBOUser represents a website account and is deliberately
 * separated from SysBOPrincipal, which represents a customer or
 * other commercial identity.
 */
export interface SysBOUser extends SysBOEntity {
  email: string;
  /** Optional single canonical international telephone number (for example +306944386714). */
  telephoneNumber?: string;
  emailVerified: boolean;

  /** When and how the current email address became verified. */
  emailVerifiedAt?: string | null;
  emailVerificationSource?: EmailVerificationSource | null;

  /**
   * Contains the securely hashed password when the user has
   * configured local authentication.
   *
   * It may be null for accounts that authenticate exclusively
   * through an external identity provider.
   */
  passwordHash: string | null;

  passwordChangedAt: string | null;

  role: SysBOUserRole;

  firstName?: string;
  lastName?: string;
  description?: string;
}

/**
 * Customer/commercial identity.
 *
 * A SysBOPrincipal does not authenticate directly.
 *
 * Authentication belongs to SysBOUser, while SysBOUserPrincipal
 * establishes the relationship between users and principals.
 */
export interface SysBOPrincipal extends SysBOEntity {
  principalType: SysBOPrincipalType;

  /**
   * Optional parent principal.
   *
   * Children do not need to be persisted separately because they
   * can be obtained by finding principals whose parentId refers
   * to this principal.
   */
  parentId: string | null;

  /**
   * Materialized canonical hierarchy root. The value is always an id; UI
   * presentation resolves names independently. Older stored snapshots may omit
   * it until they are read/re-saved through the calculated-field pipeline.
   */
  rootPrincipalId?: string | null;

  description?: string;
}

/** Canonical reusable email address. */
export interface SysEmailAddress extends SysBOEntity {
  address: string;
}

/** Many-to-many Principal <-> EmailAddress association. */
export interface SysPrincipalEmailAddress extends SysBOEntity {
  principalId: string;
  emailAddressId: string;
}

/** Canonical reusable telephone number with an explicit international country code. */
export interface SysTelephoneNumber extends SysBOEntity {
  /** E.164-style calling code, including the leading plus sign (for example +30). */
  countryCode: string;

  /** Subscriber/national number as entered for presentation. */
  number: string;

  /** Canonical normalized full number, materialized for lookup/uniqueness. */
  fullNumber: string;
}

/** Many-to-many Principal <-> TelephoneNumber association. */
export interface SysPrincipalTelephoneNumber extends SysBOEntity {
  principalId: string;
  telephoneNumberId: string;
}

/** Canonical reusable postal/street address. */
export interface SysAddress extends SysBOEntity {
  recipientOrAttention?: string;
  organization?: string;
  addressLine1: string;
  addressLine2?: string;
  addressLine3?: string;
  poBox?: string;
  postalCode?: string;
  city: string;
  stateOrProvince?: string;
  country: string;
  /** Canonical calculated compact presentation used by contact lists. */
  formattedAddress: string;
}

/** Many-to-many Principal <-> Address association. */
export interface SysPrincipalAddress extends SysBOEntity {
  principalId: string;
  addressId: string;
}

/**
 * Application known and managed by the platform.
 */
export interface SysBOApplication extends SysBOEntity {
  fullName: string;

  description?: string;
  version?: string;
}

/**
 * License associating a customer/commercial principal
 * with an application.
 */
export interface SysBOLicense extends SysBOEntity {
  /** Company-owned principal receiving the entitlement. */
  principalId: string;

  /** Exactly one platform is licensed by each SysBOLicense. */
  platformId: string;

  /**
   * Optional single-application restriction retained for backward compatibility.
   *
   * A null/omitted value represents a platform-wide license. A future richer
   * entitlement model can represent one-or-many applications and design rights
   * without changing the principal -> license -> platform ownership model.
   */
  applicationId?: string | null;

  licenseKey?: string;

  /** Optional human-readable entitlement/content rules attached to this license. */
  rules?: string;

  status: SysBOLicenseStatus;

  validFrom?: string;
  validityDuration?: SysBODurationValue | null;
  validUntil?: string | null;

  quantity: number;

  description?: string;
}

/**
 * External authentication identity associated with a SysBOUser.
 *
 * Examples of providers may include:
 *
 * - Google
 * - Facebook
 * - other OAuth/OIDC providers added later
 *
 * A SysBOUser may therefore authenticate through an external
 * provider without necessarily having a local password.
 */
export interface SysBOExternalIdentity extends SysBOEntity {
  userId: string;

  provider: string;
  providerSubject: string;

  email?: string;
  emailVerified?: boolean;
  displayName?: string;
}

/**
 * Relationship between a website SysBOUser and a
 * customer/commercial SysBOPrincipal.
 *
 * This allows:
 *
 * - one user to relate to multiple principals;
 * - one principal to relate to multiple users;
 * - the relationship type to describe the user's authority
 *   or association with that principal.
 */
export interface SysBOUserPrincipal extends SysBOEntity {
  userId: string;
  principalId: string;

  relationship: SysBOUserPrincipalRelationship;

  /**
   * Indicates the principal that should normally become the
   * user's active/default customer context.
   */
  isDefault: boolean;

  description?: string;
}

/**
 * Persistable invitation scaffold for customers created before
 * a website account exists.
 *
 * This supports the scenario where a customer/principal exists
 * before the corresponding person has registered a SysBOUser.
 *
 * `tokenHash` stores only a hash.
 *
 * The raw activation token must exist only in the invitation
 * email and must never be persisted.
 */
export interface SysBOUserInvitation extends SysBOEntity {
  email: string;

  principalId: string;

  relationship: SysBOUserPrincipalRelationship;

  requestedRole: SysBOUserRole;

  tokenHash: string;

  expiresAt: string;

  usedAt: string | null;
}
