/** Base persisted record. id is generated by the active storage provider. */
export interface SysBOEntity { id:string; name:string; createdAt:string; updatedAt:string; enabled:boolean; }
export enum SysUserRole { Admin='Admin', User='User', Guest='Guest' }
export enum SysPrincipalType { Person='Person', Company='Company', Group='Group', System='System' }
export enum SysLicenseStatus { Active='Active', Suspended='Suspended', Expired='Expired', Cancelled='Cancelled' }
export enum SysUserPrincipalRelationship { Owner='Owner', Administrator='Administrator', Member='Member', Representative='Representative' }

/** Website/security identity. name is the unique local user-name; email is also unique. */
export interface SysUser extends SysBOEntity {
  email:string; emailVerified:boolean; passwordHash:string|null; passwordChangedAt:string|null;
  role:SysUserRole; firstName?:string; lastName?:string; description?:string;
}
/** Customer/commercial identity; it does not authenticate directly. */
export interface SysPrincipal extends SysBOEntity { principalType:SysPrincipalType; parentId:string|null; description?:string; }
export interface SysApplication extends SysBOEntity { appName:string; fullName:string; description?:string; version?:string; }
export interface SysLicense extends SysBOEntity {
  principalId:string; applicationId:string; licenseKey?:string; status:SysLicenseStatus;
  validFrom?:string; validUntil?:string|null; quantity:number; description?:string;
}
export interface SysExternalIdentity extends SysBOEntity {
  userId:string; provider:string; providerSubject:string; email?:string; emailVerified?:boolean; displayName?:string;
}
export interface SysUserPrincipal extends SysBOEntity {
  userId:string; principalId:string; relationship:SysUserPrincipalRelationship; isDefault:boolean; description?:string;
}

/**
 * Persistable invitation scaffold for customers created before a website account exists.
 * tokenHash stores only a hash; the raw activation token must exist only in the invitation email.
 */
export interface SysUserInvitation extends SysBOEntity {
  email:string; principalId:string; relationship:SysUserPrincipalRelationship; requestedRole:SysUserRole;
  tokenHash:string; expiresAt:string; usedAt:string|null;
}
